name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.5]
        nodejs: [14.16.0]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v5
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs }}
      - run: npm install
      - name: Run JVM Tests
        run: sbt ++${{ matrix.scala }} jdkJVM/test
      - name: Run JS Tests
        run: sbt ++${{ matrix.scala }} jdkJS/test scalafmtCheckAll scalafmtSbtCheck
        env:
          NODEJS_VERSION: ${{ matrix.nodejs }}
